# Production Dockerfile for Poker Hand Classification
# Generated by Antigravity for ASEP HARYANA SAPUTRA

FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV MLFLOW_TRACKING_URI=https://dagshub.com/mytheclipse/Eksperimen_SML_ASEP_HARYANA_SAPUTRA.mlflow

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project
COPY . .

# Expose ports for Prometheus and MLflow (if serving)
EXPOSE 8000 5001

# Default command: Run inference test
# This validates the model is working correctly within the container
CMD ["python", "Monitoring dan Logging/7.inference.py", "--mode", "local"]
