apiVersion: 1

contactPoints:
  - orgId: 1
    name: Email-Contact-Point
    receivers:
      - uid: email-receiver-1
        type: email
        settings:
          addresses: superaseph@gmail.com
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: Email-Contact-Point
    group_by: ["alertname"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
